spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/presence_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

app:
  jwt:
    secret: your-256-bit-secret  # Gerar uma chave segura em produção
    expiration: 86400000  # 24 horas

logging:
  level:
    org.springframework: INFO
    com.presence: DEBUG